# ? TESTE PRA VER SE A CONFIG ESTÁ SENDO LIDA
server.port=9090

# ? H2 CONSOLE (URL PERSONALIZADA PRA TESTE)
spring.h2.console.enabled=true
spring.h2.console.path=/teste-h2

# ? BANCO H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ? JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true